import { determinePawnStart } from "../game/functions"

describe("determinePawnStart", () => {
    it('should return a row between 0 and 5', () => {
        const pawnStart1 = determinePawnStart()
        const pawnStart2 = determinePawnStart()
        const pawnStart3 = determinePawnStart()
        const pawnStart4 = determinePawnStart()
        const pawnStart5 = determinePawnStart()
        expect(pawnStart1.pawnRow).toBeGreaterThanOrEqual(0)
        expect(pawnStart1.pawnRow).toBeLessThanOrEqual(5)
        expect(pawnStart2.pawnRow).toBeGreaterThanOrEqual(0)
        expect(pawnStart2.pawnRow).toBeLessThanOrEqual(5)
        expect(pawnStart3.pawnRow).toBeGreaterThanOrEqual(0)
        expect(pawnStart3.pawnRow).toBeLessThanOrEqual(5)
        expect(pawnStart4.pawnRow).toBeGreaterThanOrEqual(0)
        expect(pawnStart4.pawnRow).toBeLessThanOrEqual(5)
        expect(pawnStart5.pawnRow).toBeGreaterThanOrEqual(0)
        expect(pawnStart5.pawnRow).toBeLessThanOrEqual(5)    
    })
    it('should return a col between 0 and 7', () => {
        const pawnStart1 = determinePawnStart()
        const pawnStart2 = determinePawnStart()
        const pawnStart3 = determinePawnStart()
        const pawnStart4 = determinePawnStart()
        const pawnStart5 = determinePawnStart()
        expect(pawnStart1.pawnCol).toBeGreaterThanOrEqual(0)
        expect(pawnStart1.pawnCol).toBeLessThanOrEqual(7)
        expect(pawnStart2.pawnCol).toBeGreaterThanOrEqual(0)
        expect(pawnStart2.pawnCol).toBeLessThanOrEqual(7)
        expect(pawnStart3.pawnCol).toBeGreaterThanOrEqual(0)
        expect(pawnStart3.pawnCol).toBeLessThanOrEqual(7)
        expect(pawnStart4.pawnCol).toBeGreaterThanOrEqual(0)
        expect(pawnStart4.pawnCol).toBeLessThanOrEqual(7)
        expect(pawnStart5.pawnCol).toBeGreaterThanOrEqual(0)
        expect(pawnStart5.pawnCol).toBeLessThanOrEqual(7)    
    })
})